name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit PIN'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Initializing Setup
      shell: pwsh
      run: ./setup.ps1

    - name: Starting CRD
      shell: pwsh
      run: |
        $authCode = '${{ github.event.inputs.authcode }}'
        $pinCode = '${{ github.event.inputs.pincode }}'
        Start-CRDProcess -AuthCode $authCode -Pin $pinCode

    - name: Keep Alive
      shell: pwsh
      run: ./timeout.ps1
